services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/configs:/etc/nginx/conf.d
      - app_static_volume:/var/www/static/
    depends_on:
      - app
    ports:
      - "80:80"
  app:
    build:
      context: .
      dockerfile:
        docker/app/Dockerfile
    env_file:
      - flask_app/settings/.env
    labels:
      NAME: "videoseed-api"
volumes:
  app_static_volume:
    driver: local
